### ISSUE TITLE
CT check for not existing site column

### ISSUE THREAD

**Issue by braegelno5** [OfficeDev/PnP-Sites-Core#104]
On SP Prem it is possible to rollout a wsp with a ct definition with one ore more not existing linked fields. This bug comes only on light if you use this ct..
So if we export the ct to our xml we need a check for really existent fields. On the CSOM import side we get big trouble..
Tomorrow if I have access to my production environment I will upload a patch for this..

**Comment by PaoloPia** [comment]
Hi Torsten, Is this issue still open, even after the changes we made in the latest months? Thanks.

**Comment by braegelno5** [comment]
if i remember this correct, there was also a pr for this.. anyway i have changed the known wsp on our side, where i detected this behavior. On the other side we should have such a check in the engine, and the engine should only write an error to the log for the not existing objects and never stop there work.

**Comment by PaoloPia** [comment]
Thanks Torsten, we usually prefer to block the provisioning in case of any error, instead of proceeding making the user making wrong assumptions. I mean: if we can't properly provision the template, we prefer to stop the provisioning and make the user aware of it, rather than logging a line an proceeding with a potentially inconsistent result. I will close this issue, because there should be a merged PR for this. If you will experience it in the future, I will be more than happy to re-open it. Thanks again.

**Comment by braegelno5** [comment]
not so hurry italian man;) i have make a new pr (#401), and this will throw an error with field id and text, so the enduser using powershell will be able to find the bug inside the template xml.

**Comment by PaoloPia** [comment]
Thanks for your contribution. I will double-check the PR and let you know.
