### ISSUE TITLE
What is your opinion about spmeta2?

### ISSUE THREAD

**Issue by cveld** [OfficeDev/PnP-Sites-Core#150]
I just found out that there is yet another popular provisioning framework, called spmeta2:
http://docs.subpointsolutions.com/spmeta2/utils/

Are there any plans to join efforts?

**Comment by VesaJuvonen** [comment]
We are absolutely open for collaborating and contributions from any partner and customer towards PnP. There are slightly different capabilities within SPMeta2, like server side support, which PnP is not targeting, but it's absolutely a great tool as well.

**Comment by vimalpatel1826** [comment]
@VesaJuvonen spmeta supports a lot of extention methods and helper classes for provisioning site columns, termsets, terms, content types etc in batches like using fielddefinition collection objects. Does PnP supports or has such capability. Can we still use the POCO definitions with PnP.

**Comment by VesaJuvonen** [comment]
@vimalpatel1826 - PnP support full POCO definitions. You can start from scratch with code or from live site and get the object model based definition of the configurations. PnP supports, columns, term sets, term groups, content types, views, lists, all site level settings, all list level settings exposed in CSOM etc. Full list of the schema (represents objects as well, but you can serialize to XML/JSON) is available from here - https://github.com/SharePoint/PnP-Provisioning-Schema/blob/master/ProvisioningSchema-2015-05.md.

You do not need to do serialization, but that's pretty common with enterprise scenarios, so that you can for example provide UI to chose from different templates (see PnP Partner Pack as starter kit solution - https://github.com/SharePoint/PnP-partner-pack). You can simply export object model definition from live site and modify that in memory either using managed code or PowerShell (with PnP PowerShell - http://aka.ms/sppnp-powershell). Obviously also delta handling is supported with templates.

There are quite a few remote provisioning framework there and if you chose to use SPMeta2, you really don't chose badly... it's a great open source remote provisioning framework. It's just matter of evaluating what are your use cases and which solutions is the best match.

**Comment by vimalpatel1826** [comment]
@VesaJuvonen  I appreciate your prompt response. It is very helpful. In coming days I am going to refer samples n documentations suggested by you and from SharePoint/PnP branch. I will surely get back to you in case I have further queries.
