### ISSUE TITLE
Remove-SPOContentTypeFromList not working on sub sites

### ISSUE THREAD

**Issue by peterstilgoe** [OfficeDev/PnP-Sites-Core#181]
I have an issue with the following on the default 'Documents' library that gets created when provisioning a new site:

 add-SPOContentTypeToList -List "Documents" -ContentType "Team site document" -DefaultContentType 
** This works, a new content type is added called 'Team site document' and is now the default CT **

 Remove-SPOContentTypeFromList -List "Documents" -ContentType "Document" 
** This doesn't work, the command runs but whatever I try the 'Document' content type never gets removed **

With testing the above does work on the top level site / root web but does not work on subsites.

Speaking to Luis Manez on Yammer he thinks its a similar issue to this:

https://github.com/OfficeDev/PnP-Sites-Core/issues/165

**Comment by luismanez** [comment]
I'm pretty sure that the reason is because PS command is calling GetContentType without specifying that it has to search in the Site collection too (and by default is False). I'll try to fix this issue, but I'm waiting for confirmation from @erwinvanhunen that my proposal solution is valid and I'm not missing anything.

**Comment by erwinvanhunen** [comment]
The fix for this was already in place. I will close this issue.
