### ISSUE TITLE
Setting a web part's contents does not properly handle the CDATA

### ISSUE THREAD

**Issue by lanegoolsby** [OfficeDev/PnP-Sites-Core#183]
If you set a web part's Contents directly in the ProvisioningTemplate.Pages.Page.WebPart the CDATA gets encoded (e.g. < gets turned into &lt;). This causes the template to be invalid.

**Comment by VesaJuvonen** [comment]
Hi lanegoolsby, this one is slightly problematic, since it modifies automatically generated code file based on the provisioning schema. All of the schema changes for PnP are processed first in the PnP-Provisioning-Schema repository and the moved to the Core component. 

We are however just in process to release a new schema version and will closely look on this particular finding as well, so that the actual issue will be fixed. Implementation for the new schema release is currently planned to be part of the January 2016 master merge.
