### ISSUE TITLE
RemoveExistingContentTypes does not work on existing lists

### ISSUE THREAD

**Issue by joakimlong** [OfficeDev/PnP-Sites-Core#337]
When defining an already existing list by for example 
`<pnp:ListInstance Title="Shared Documents" TemplateType="101" Url="Shared Documents" ContentTypesEnabled="true" RemoveExistingContentTypes="true">`

the RemoveExistingContentTypes attribute is not applied. It's only implemented for CreateList which makes it impossible to use an existing list and replace the standard content type with my own content type.

**Comment by PaoloPia** [comment]
Hi,
Thanks for your feedback. I'm not sure that I got your point. However, removing existing content types from an already existing list instance could be dangerous, and if the content type is in use it is also impossible and would lead to an exception. That's why we intentionally do not remove artifacts while applying a template. We do remove content types during creation of a new list, because at that point in time you don't have contents and it is not a dangerous operation. I will close this issue, but feel free to write me if I misunderstood your point. Thanks.

**Comment by joakimlong** [comment]
Hi Paolo,

Thanks for your response. I'm using the pnp core component to set up new
sites using an xml template. It works really great! But what I ran into was
that it is impossible for me to add a content type to a library and then
remove the already existing one(s). The attribute RemoveExistingContentTypes is
exactly what I need, however this functionality is only implemented when
creating new lists, not when updating existing ones. For example, there is
already a Documents library when I create a team site and I want change the
content types used within it.

I agree on that it might be a dangerous operation, but omitting
functionality just because it might cause trouble if people use it in the
wrong way is maybe not the best way to go?

Again, thanks for coming back to me.

/Joakim



2016-02-22 0:26 GMT+01:00 Paolo Pialorsi <notifications@github.com>:
