### ISSUE TITLE
Provisioning : UpdateList on a DocumentLibrary with EnableMinorVersions fail on SharePoint On-Premise. 

### ISSUE THREAD

**Issue by drdeteck** [OfficeDev/PnP-Sites-Core#409]
The problem is in `ObjectListInstance.cs` method `UpdateList`.

We load the `MajorWithMinorVersionsLimit` property of the existing list only for SPO (around line 660). 

Then when we set the `MinorVersionLimit` value, _which should only be for SPO_ (around line 767) we read the value of `MajorWithMinorVersionsLimit` but there is no `#if !CLIENTSDKV15 #endif` check.

So, since the property isn't loaded, but is read (SP OnPrem), the CSOM (Microsoft.SharePoint.Client.dll v15) throw an error :

```
The property or field 'MajorWithMinorVersionsLimit' has not been initialized. It has
not been requested or the request has not been executed. It may need to be explicitly requested.
```
---

Additionnaly, the `MajorWithMinorVersionsLimit` and the `MajorVersionLimit` exist in CSOM v15, it's the `MinorVersionLimit` that doesn't exist. Shouldn't the Provisioning Framework be reflecting that ?

Also, on another note, the `MajorVersionLimit` is never loaded for SPO but is read. Shouldn't that property be loaded first ?

**Comment by drdeteck** [comment]
BUMP ?!

**Comment by erwinvanhunen** [comment]
Sorry for long delay. I just doubled checked this issue with the current version of the provisioning engine towards SP2013 on-premises, and am not able to reproduce this. Many changes have been made to the engine since this issue was posted and I will assume it as being solved. If you do not agree, please do not hesitate to re-open this issue.
