### ISSUE TITLE
OOTB default content types not removed during provisioning

### ISSUE THREAD

**Issue by gavinbarron** [OfficeDev/PnP-Sites-Core#476]
When adding a new default content type to a List or Library the OOTB defaults of Item and Document are left bound to the List/Library

This occurs when they are not in the list of contenttype bindings

**Comment by PieterVeenstra** [comment]
In your list instance you have to set to remove existing contenttypes like this:

< pnp:ListInstance RemoveExistingContentTypes="true"

By design the content types that were either added by the feature of the list or that were added through any other means will remain on the list. With the above setting these will be removed ( if not in use).

**Comment by gavinbarron** [comment]
Thanks Pieter!
