### ISSUE TITLE
Template Engine does not store and restore list settings for Quick Edit and Dialog

### ISSUE THREAD

**Issue by lafe** [OfficeDev/PnP-Sites-Core#69]
The templating engine does not store and therefore also does not restore the list settings "Allow items in this list to be edited using Quick Edit?" and "Launch forms in a dialog?".

I know that the reason is that the properties "NavigateForFormsPages" (for dialogs) and "DisableGridEditing" are missing in the CSOM, but maybe an additional issue can help to add these missing properties.

**Comment by VesaJuvonen** [comment]
Thx Lars. Best forum to drive new capabilities in the CSOM/REST side would be user voice. We are linked with the PnP on that work as well, but those are the numbers which actually counts when resource prioritization is done by feature crews. 

Closing the issue from here, since we can't fix this with PnP for now and rather want to reduce the noise of those things which we can fix. Would however suggest to create a user voice entry for all things which are missing and are important.
