### ISSUE TITLE
Blank page after applying Regionalsettings

### ISSUE THREAD

**Issue by KbWorks** [OfficeDev/PnP-Sites-Core#715]
Hi All,

i have found a bug when applying regionalsettings and directly after security:
   <pnp:RegionalSettings LocaleId="2057" TimeZone="4" />
      <pnp:Security>
Creates a white page directly after applying these to steps

#### Which PnP repository to report the issue?
- PnP Sites Core - https://github.com/OfficeDev/PnP-Sites-Core version 2.6.1608.0

*You can delete this section after you have confirmed target repository for your submission.*

#### Category
[X ] Bug
[ ] Enhancement

#### Environment
[X ] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

Expected behavior that the site provisions correctly with correct regional settings

#### Observed Behavior
after creating subsite and applying 
xmltemplate schema 2015/12
 <pnp:RegionalSettings LocaleId="2057" TimeZone="4" />
      <pnp:Security>
</pnp:Security>
it gives blank pages on all libraries. only the settings pages are available.

excluding regionalsettings gives correct result for provisioning except the settings ofcourse.

thanks for solving in advance.

Kr,

Paul

**Comment by skaggej** [comment]
+1 for this issue

**Comment by DeChrist** [comment]
Sharing your "RegionalSettings" element may help to match your issue with others, like the following one.

I had a similar issue in SharePoint On-Prem. This allowed me to check the ULS and trace the issue to an exception trying to set a calendar type for the web.
I traced this to the attribute "CalendarType" of the "RegionalSettings" element.
Before August Update, a value of "none" for this attribute was supported and kept the default setting for the Web Calendar Type (note that this was generated by a Get-SPOProvisioningTemplate).
After August Update, apparently this is no longer the case, so a valid supported value must be specified.
The issue disappeared when I used `CalendarType="Gregorian"`.
Thanks to confirm if your issue is the same.

**Comment by VesaJuvonen** [comment]
Like @DeChrist noted, any change for sharing the regional setting element or template which was used for this. Having a repro is always important and makes the fix so much easier to do. You can past in the element section here or send that directly with personal email. Either way works.

**Comment by KbWorks** [comment]
Hi Vesa,

Thanks at least it is a nice workarround :-) and i only work online for now so no ULS at the moment :-(

kr,

Paul

**Comment by jansenbe** [comment]
Thanks for reporting this @KbWorks and @skaggej. With the latest version we allowed setting CalendarType but apparently setting it to none is allowed using API (not in UI) and has the strange side effect of showing the home page as blank. We've fixed this in the dev branch and in case you need to fix your existing sites you can set CalendarType back to a known value like Gregorian. A workaround for your provisioning templates is adding the CalendarType property.

**Comment by paulbuzzby** [comment]
Just suffered from this issue today, deployed a script to production and all the sites are "blank". Glad the fix is easy, just need to run the scripts again.
