### ISSUE TITLE
Create Site Column of TaxonomyFieldType breaks Site Collection site columns page

### ISSUE THREAD

**Issue by JBeerens** [OfficeDev/PnP-Sites-Core#87]
Core: 1.6.915.0

When I add a new SiteField of type TaxonomyFieldType and assign an invalid term set to property TermSetId, the Site Collection site columns will become unreachable.

< Property > 
< Name >TermSetId</ Name>
< Value xmlns:q2="http://www.w3.org/2001/XMLSchema" p4:type="q2:string"       xmlns:p4="http://www.w3.org/2001/XMLSchema-instance">{termsetid:Document:UnknownTermSet}</ Value>
</ Property>

**Comment by cbrotto** [comment]
Same here (2.1.1602.0) :(
It seems like accessing the Fields collection of the web is throwing an error (also when accessing the fields collection via rest/csom).
Any suggestion about a way to get back (is there a way to remove the field without accessing the fields collection, i.e. web.Fields.GetById(...).DeleteObject?).
Thanks!

**Comment by PaoloPia** [comment]
Hi JBeerens and Ciao Claudio,
are you on-premises or in SPO? BTW, have you tried to remove the wrong field with the PnP PowerShell extensions (I mean with Remove-SPOField)?

**Comment by cbrotto** [comment]
Ciao Paolo,
SPO :)
Yes, I've tried but unfortunately it breaks at web.Fields.GetById.
I guess the fields collection is somehow inaccessible, since I'm getting the same error for example invoking _api/web/fields.

**Comment by PaoloPia** [comment]
Well, can you share a failing template to play with? Have you tried accessing the field directly by ID, I mean instead of querying for _api/web/fields ... going through something like: _api/web/fields(guid'672D9500-5649-49ae-8166-777F40527874') ... just wondering ...

**Comment by cbrotto** [comment]
Ciao Paolo,
sure, here it is!
[Provisioning.Taxonomy.txt](https://github.com/OfficeDev/PnP-Sites-Core/files/122855/Provisioning.Taxonomy.txt)
The issue (my fault) is a mispelled Term Set Name (TermSetId property in the customization element).
I tried to get direct access to the field, but with no luck, probably because you have to go through the field collection in order to get a reference to one specific field (I mean, there's no web.GetFieldById that bypasses the Fields collection, at least for what I know).

I was curious and made some further investigations (on-prem, SP2013): 
- Created a Taxonomy Field (web.Fields.AddFieldAsXml using the Server Object Model) using an invalidCustomization element
- Access to web.Fields.SchemaXml -> no error, xml contains the field
- Access to web.Fields.GetFieldByInternalName("MyBadField") -> error
- Access to web.Fields.GetFieldByInternalName("Title") -> ok
- Navigation to .../_layouts/15/mngfield.aspx (Site Settings -> Site Columns) -> error
- Navigation to .../_layouts/15/FldEdit.aspx?Field=MyBadField -> error
- Navigation to .../_layouts/15/FldEdit.aspx?Field=Title -> error

I think this is more of a SharePoint issue than a Provisioning Engine issue.
:(

**Comment by PaoloPia** [comment]
Claudio, I cannot download the file (don't ask me why :) ...) can you please send it to me by email, as an attachment? Thanks.

**Comment by PaoloPia** [comment]
Claudio, can you share the template by email? Thanks.

**Comment by PaoloPia** [comment]
Thanks, now I have a test scenario. I will try to find a solution ... no guarantee, of course :) ...

**Comment by erwinvanhunen** [comment]
Closing this issue as fix has been merged.
