### ISSUE TITLE
Builtin contenttypes exported in ListInstance

### ISSUE THREAD

**Issue by SchauDK** [OfficeDev/PnP-Sites-Core#90]
The export behaviour of content types on list instance has been changed from

                        if (ct.Parent != null)
                        {
                            //Add the parent to the list of content types
                            if (!BuiltInContentTypeId.Contains(ct.Parent.StringId))
                            {
                            list.ContentTypeBindings.Add(new ContentTypeBinding { ContentTypeId = ct.Parent.StringId, Default = count == 0 });
                            }
                        }
                        else
                        {
                            list.ContentTypeBindings.Add(new ContentTypeBinding { ContentTypeId = ct.StringId, Default = count == 0 });
                        }

to

                        list.ContentTypeBindings.Add(new ContentTypeBinding
                        {
                            ContentTypeId = ct.Parent != null ? ct.Parent.StringId : ct.StringId,
                            Default = count == 0
                        });

It means that if ContentTypesEnabled on the list is False on import, it will try to add the buildin content types and fail because they already exist.

I suggest that you revert the change or please explain the reason for the change.

Thanks.

**Comment by VesaJuvonen** [comment]
This issue is now fixed with the updated Oct release. We do export oob CTs to list definition as well, but only add them in to the other side, if they do not exist in the list at that stage. This is because someone might also customize oob document library by adding oob CTs to it and we'll need to take that scenario into account. With the updated Oct version we should be good. 

If that's not the case, please re-open the issue. Thx for reporting the issue.
